### PR TITLE
Add ability to cross-build the app

### PR DESCRIPTION
**Pull request by sindresorhus**
Will be nicer when the following is fixed:
- https://github.com/maxogden/electron-packager/issues/40
- https://github.com/maxogden/electron-packager/issues/35
- https://github.com/maxogden/electron-packager/issues/36
- https://github.com/maxogden/electron-packager/issues/37

### CODE REVIEW

**Comment by sindresorhus** [comment]
@maxogden @jden

**Comment by max-mapper** [comment]
cross-compile as in re-compile native addons for another platform (e.g. with node-gyp?)

**Comment by sindresorhus** [comment]
@maxogden Misleading title, meant cross-build.

I could integrate https://github.com/paulcbetts/electron-rebuild for that, but not sure if it's worth the extra bloat in a boilerplate.

**Comment by sindresorhus** [comment]
Gonna wait with this until the mentioned issues are resolved. https://github.com/sindresorhus/electron-boilerplate/issues/5

**Pull request closed without merging**
