### PR TITLE
feat: dist task to pack in a distributable format

### PR DESCRIPTION
**Pull request by develar**
Add `dist` task to pack in a distributable format.

### CODE REVIEW

**Comment by develar** [comment]
Ping :)

**Comment by develar** [comment]
@sindresorhus Ping :)

@sindresorhus What do you think if this project will be changed to use https://github.com/electron-userland/electron-webpack? Ability to use modern javascript and so on.

**Comment by sindresorhus** [comment]
> @sindresorhus Ping :)

Sorry, I'm in the process of rewriting this boilerplate to use `electron-builder`, but I've been held up by getting https://github.com/sindresorhus/caprine/pull/240 merged first, so I can test the boilerplate in practice.

> What do you think if this project will be changed to use electron-userland/electron-webpack? Ability to use modern javascript and so on.

I don't really see much benefit to that. You can already use most modern JS features in Electron, like async/await. I think it would be better for a higher-level boilerplate.

**Comment by KararTY** [comment]
@sindresorhus ETA on that?

**Comment by sindresorhus** [comment]
The rewrite is finally done.

**Pull request closed without merging**
