### PR TITLE
Add devtron in development mode

### PR DESCRIPTION
**Pull request by JanMalch**
This PR adds the [devtron](https://electronjs.org/devtron) extension in development mode.

### CODE REVIEW

**Comment by sindresorhus** [comment]
`electron-debug` already adds it if you add Devtron as a dev dependency: https://github.com/sindresorhus/electron-debug#activates-devtools-extensions However, that doesn't seem to work when `nodeIntegration` is off. I think it would be better to fix that in `electron-debug` first.

**Comment by JanMalch** [comment]
Ah, I didn't see that, my bad.
I can look into `electron-debug`.

**Comment by JanMalch** [comment]
I added a `preload.js` to `electron-debug` (https://github.com/JanMalch/electron-debug/commit/e2f4a5614236cbae43677d6920b9697c55fb776e), which can be imported in the boilerplate's [`preload.js`](https://github.com/sindresorhus/electron-boilerplate/blob/249459e09bfbafe9c29916e8e706e0baf3b1e630/preload.js).

If this is a good solution I can extend the README accordingly.

**Comment by sindresorhus** [comment]
I was thinking reducing the boilerplate even more by taking advantage of https://electronjs.org/docs/api/session#sessetpreloadspreloads in `electron-debug`.

**Comment by reZach** [comment]
@JanMalch, I've had no success in turning on Devtron in development branches in my personal projects, have you got Devtron working? [A handful of people](https://github.com/electron-userland/devtron/issues/111) seem to think the project is already dead.

**Comment by sindresorhus** [comment]
How can we move this pull request forward?

**Comment by JanMalch** [comment]
I also got the impression that it's dead and in the end I didn't use it either. I can take a look at it again in the next few days.

**Comment by sindresorhus** [comment]
Bump

**Pull request closed without merging**
